
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    tier: frontend
    app: web  
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web  
    spec:
      containers:
        - name: web
          image: divya120/web
          livenessProbe:
            httpGet:
              path: /dashboard
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          
